pyinstaller_spec: disable UPX
It breaks everything. I get this when trying to import PyQt5 when UPX'd:

   ImportError: DLL load failed: Invalid access to memory location.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>